### ISSUE TITLE
Phrase interlocking, different kinds of phrase endings, cadence annotations

### ISSUE THREAD

**Issue by johentsch** [DCMLab/standards#12]
Quite frequently, a phrase ending is at the same time the beginning of a new phrase (phrase interlocking). We could account for such instances with an alternative to`\\` (e.g. `\`). On the other hand, currently phrases are always considered to begin where the last one ended so the question is: What different kinds of phrase endings can be cleanly separated and which of them do we want to account for?

Another question that was raised at an earlier point was: "Should we make it possible to add cadence information?" This could be easily done by allowing either a fixed vocabulary or free text to follow `\\`, e.g. `\\PAC` or `\\quintabsatz`.

**Comment by fabianmoss** [comment]
I would be in favor to include the ability for cadence types. However, we should think about what kinds of labels we want to allow. Cadences and phrases are not the same thing (although the definition of phrase is not really clear to me).

**Comment by allorens** [comment]
I agree it would be necessary to include a symbol for phrase interlocking (\). It is very frequent in some repertoires and the use of \\ is highly problemmatical, as, after the \\ we need to add an annotation that is harmonically equal to the one ending the phrase but that now falls 'off' beat and therefore the position of which is not real. Would it be possible to get one \ annotation to be duplicated in a way that, in the same position, it stands for both phrase end and phrase start?

**Comment by allorens** [comment]
Second issue (in line with @fabianmoss): what are you telling annotators 'is' a phrase? 
- Are you taking into account stylistic changes? (for instance, pre-Classical vs Classical phrase construction)
- Are you assigning a phrase end everytime there is a cadence? This is problemmatical. In our repertoire I've frequently found a clear half-cadence (and even a IAC or PAC) before the vocal coloratura that, 1 or 2 bars later, finally cadences in a I:PAC.

**Comment by allorens** [comment]
Some after-meeting thoughts:
If ``\`` or ``\\`` are left to mark the end event of cadences and/or phrases, the duration of the phrases could be calculated taking into account phrase start labels only. However, I see two issues:
- G.P. and other such events that we may want to separate from the phrases but which we don't want to count as a phrase in order not to get a total number of phrases higher than reality. If phrase starts are marked ``//``, G.P. and the such could be labelled ``/`` (or vice versa) to distinguish them from actual phrases.
- Phrase interlockings: is/are the common event(s) going to be counted as part of the ending or of the starting phrase? Or of both and then substracted ``x1`` from the total calculation?
