### ISSUE TITLE
Hierarchical phrase structure annotation?

### ISSUE THREAD

**Issue by allorens** [DCMLab/standards#13]
In realtion to the thread on phrase endings, are you thinking of allowing for hierarchical phrase structure annotation? If so, how?

I'm tinking of Caplinean theory, or at least in terms of phrases and periods (and, in big pieces, sections). Including this kind of annotation would permit analysis of harmony and phrase structure together, which would mean a step forward I guess. We made some preliminary trials by annotating this as text data on the bass voice, but perhaps it would be useful to include it along with the harmonic labels. What do you think?

**Comment by johentsch** [comment]
Our discussions yielded a new but not hierarchical way of phrase annotations. We agreed on leaving hierarchical phrase structure to a separate form annotation standard.
