### ISSUE TITLE
Relative-to-previous-key modulations

### ISSUE THREAD

**Issue by allorens** [DCMLab/standards#18]
The current annotation standard for modulations labels them in relation to the principal key of the piece. Whereas that has great advantages, this makes we lose the info of how the keys move from one to the next. In other words, a chain of modulations such as I-V-IV doesn't say anything of the I-VII that it is established between the V and the IV (the higher-order V was already felt as a I). So would you think it would be useful to include a feature in the code that extracts that info too?

**Comment by johentsch** [comment]
IMHO, this is a project-specific transformation of raw data and should be discussed in a different context because it does not impact on the annotation standard. If you think it does, feel free to reopen the issue.
