### ISSUE TITLE
What is an augmented seventh chord? Size of the seventh

### ISSUE THREAD

**Issue by johentsch** [DCMLab/standards#24]
The mapping from chord features to chord types goes as follows:

| Root | Type | Inversions   | Chord type              |
|------|------|--------------|-------------------------|
| RN   | <NA> | <NA>, 6, 64  | Major triad             |
| rn   | <NA> | <NA>, 6, 64  | Minor triad             |
| rn   | o    | <NA>, 6, 64  | Diminished triad        |
| RN   | +    | <NA>, 6, 64  | Augmented triad         |
| RN   | <NA> | 7, 65, 43, 2 | Dominant seventh        |
| rn   | <NA> | 7, 65, 43, 2 | Minor seventh           |
| rn   | o    | 7, 65, 43, 2 | Diminished seventh      |
| rn   | %   | 7, 65, 43, 2 | Half-diminished seventh |
| RN   | M    | 7, 65, 43, 2 | Major seventh           |
| rn   | M    | 7, 65, 43, 2 | Minor major seventh     |
| RN   | +    | 7, 65, 43, 2 | Augmented seventh       |

The only problem is, that for all seventh chords the size of the seventh is defined but not for the augmented one. I suggest to fix it to always have a major seventh because in the case of the minor seven the chord is so much more likely to be analysed as an alterated dominant `V7(#5)`.

**Comment by adriannagel** [comment]
Is it not possible to have two different symbols for the augmented seventh chord like RN+7 (-> which is a minor seventh) and RH+M7 (-> which is a major one)?

**Comment by apmcleod** [comment]
For me (as someone using the dataset with a music performance background, but no real classical theory education), a brief search when using the data lead me to [this page](https://en.wikipedia.org/wiki/Augmented_seventh_chord) (and other similar pages) that suggest that a standard augmented 7th chord has a minor 7th. The alternative seems to be commonly called "Augmented major 7th".

It's important that a naive user doesn't make the wrong assumption given the labels.

So, I think @adriannagel's suggestion is a good one.

**Comment by apmcleod** [comment]
Or at least, if we use RN+7 to mean something other than an augmented triad with a minor 7th, it needs to be made extremely clear.

**Comment by johentsch** [comment]
Great everyone, that's what we agreed on.

Solution: `V+7` has a minor seventh, `V+M7` has a major seventh. For consistency, allow for `VoM7`, too.
