### ISSUE TITLE
Changes bigger than 13

### ISSUE THREAD

**Issue by adriannagel** [DCMLab/standards#27]
There are sometimes causes for symbols larger than 13. For example: In a sixth chord, the sixth is present and its octave is suspended. If there would be a "7" in the brackets, you would assume that this first sixth is not already there. So, I think it would be useful to have these larger numbers.

Mendelssohn String Quartet No 1 op 12 E flat major
<img width="1163" alt="Bildschirmfoto 2020-07-15 um 11 00 23" src="https://user-images.githubusercontent.com/48351266/87526027-96711000-c68a-11ea-966c-607ccf83c54d.png">

**Comment by johentsch** [comment]
Great observation if you want to account for the fact that Ab is present on beat 1.

Would you be so kind as to provide a screenshot with clefs, key signature and bar numbers and to name the piece, plese?

**Comment by adriannagel** [comment]
added bigger screenshot!

**Comment by johentsch** [comment]
Fixed with v2.2.0

**Comment by johentsch** [comment]
Fixed with v2.2.0
