### ISSUE TITLE
Upbeat anticipating the following downbeat harmony

### ISSUE THREAD

**Issue by allorens** [DCMLab/standards#28]
I'm bringin an extreme case of an upbeat anticipating the following downbeat harmony, as in this piece this note receives 2 different harmonisations (in the example below, the melodic `C`  appears over both the minor tonic (`f`) and the dominant chords). Whereas the inclusion of a `V` label would seems straightforward when relevant, what would you tell the annotators to do at the beginning of the piece?
- include a `i` for both the anacrusis and the downbeat tonic (which would go counter the rule of non-repeated consecutive labels)
- label as `i` just the anacrusis (which would go counter the downbeat harmonic configuration of the piece)
- label as `i` just the downbeat (which, when looking for harmonic-rhythmic patterns, would make one miss the matching with the frequent `V` or `viio` anacruses)

Would you make a generalisable rule?

a) start of the piece: tonic harmonisation
![image](https://user-images.githubusercontent.com/61057980/87033020-c5e4d000-c1e5-11ea-9c37-bf141fc62a6a.png)

b) example of dominant harmonisation 
![image](https://user-images.githubusercontent.com/61057980/87033226-1e1bd200-c1e6-11ea-83de-ebe8c0cea423.png)

Source: _Non ha ragione, ingrato_ from Domenico Natale Sarro's _Didone abbandonata_ (1724)

**Comment by johentsch** [comment]
Interesting. So far no one was told to keep subsequent metrical analysis in mind so our annotators would without any doubt but the `.f.i` on the anacrusis (second option).

I will suggest to include this issue in the discussion about segmentation in general, where metrical segmentation would be one that, so far, has been taken into account by annotators more on an intuitive, not on a systematic level.

**Comment by johentsch** [comment]
It is now allowed to repeat identical labels. DCML annotators are still discouraged to do it. This needs to be added to the docs.
