### ISSUE TITLE
annotation of special chords

### ISSUE THREAD

**Issue by allorens** [DCMLab/standards#33]
The `special` chords `Ger` and `Fr` are currently annotated with a preceding `.` , whereas `It` doesn't have such `.` Even if there's no possible confusion with an initial `key` label, it might be more consistent to start all `special` harmonies with `.`

**Comment by johentsch** [comment]
You can always start any label with `.` because it's inconsequential. Actually that's just a workaround necessary for all labels starting with a note name. So yes, feel free to write `.It6` if you like it better.

**Comment by allorens** [comment]
I found out because I made the 'mistake', but this is not mentioned anywhere in the guidelines. It reads 'The latter [`It`] actually does not need an initial dot because it does not start with a note name', but this does not mean it CAN be used if preferred. Perhaps it could be said more clearly.
