### ISSUE TITLE
Secondary dominants in passages of temporary change of the tonic

### ISSUE THREAD

**Issue by adriannagel** [DCMLab/standards#35]
In the standard there is the difference between a complete modulation (V.ii7 or ii.V7) and a temporary change of the tonic (V/ii ii). In my opinion, that is a very good differentiation. However in some passages of temporary changes sometimes there are secondary dominants which can not be annotated in a right way.

Here is a example from Mendelssohn String Quartet op 12 No 1 E flat major:

<img width="899" alt="Bildschirmfoto 2020-07-15 um 11 21 53" src="https://user-images.githubusercontent.com/48351266/87528922-88bd8980-c68e-11ea-9332-0c60014c812b.png">

Here the viio7/VII and V65/VII is not really related to VII. I like to suggest for this cases an annotation in this way: viio7/V/iii V65/V/iii

**Comment by johentsch** [comment]
Yes, absolutely! The latest published version (v2.1.0) already allows for this. That is a good example to include in the FAQ, thanks!
