### ISSUE TITLE
chord_type for augmented 6th chords

### ISSUE THREAD

**Issue by allorens** [DCMLab/standards#38]
For some reason in the tables for the Mozart sonatas, augmented 6th chords are classified as major triads, even though they are translated well into their respective "real" chords.
![image](https://user-images.githubusercontent.com/61057980/88579616-9e499080-d04a-11ea-954e-87864b395186.png)

Similar chords without the ``special`` feature are classified well:
![image](https://user-images.githubusercontent.com/61057980/88581549-9fc88800-d04d-11ea-81d1-ae0c950a3fe5.png)

Is there an issue in the ``featuretotype`` function?

**Comment by johentsch** [comment]
This happens when `features2type` is applied before replacing the special symbols `Ger, Fr, It`. Fixed in the mozart_loader.
